### ISSUE TITLE
Does the crawler support sitemap-index

### ISSUE THREAD

**Issue by tobiasmcvey** [nlnwa/veidemann-harvester#161]
Does this crawler support sitemap-index?

At NAV we use sitemap-index and link to sitemap.xml files from there.

See https://www.nav.no/robots.txt and https://www.nav.no/sitemap/sitemap-index.xml

We recently developed an app that will manage this for all our subdomains. This is being adopted in phases so some subdomains will only use sitemap files until they have an index file.

**Comment by Langvann** [comment]
Unfortunately, the crawler does not yet support sitemaps, but it’s on our roadmap.  

Thank you for submitting the information, we will get back to you when we start planning for sitemaps.
